### ISSUE TITLE
NavigateAsync to pages

### ISSUE THREAD

**Issue by gvhung** [naveasy/Naveasy#7]
How I can call NavigateAsync with multi pages like PRISM?

like this: NavigateAsync("NavigationPage/Page1/Page2")

Thanks.

**Comment by ederbond** [comment]
As of now we don't have support to multipage navigation in a single call.
But I think you can archive the simililar behavior by doing it in 2 steps:

Step 1
```csharp
var parameters = new Page2Args
{
    AutoNavigateToPage2 = true
};

NavigateAsync<INavigationPage<Page1ViewModel>>( parameters.ToNavigationParameters());
```

Step 2

```csharp
public class Page1ViewModel
{
     public override void OnInitialized(INavigationParameters parameters)
     {
          var args = parameters.GetValue<Page2Args>();
          
          if (args.AutoNavigateToPage2 == true)
          {
               _navigationService.NavigateAsync<Page2ViewModel>();
          }
     }
}
```

We will try to add support to multi level page navigation in future versions.
If you would like to contribute to speed-up adding this feature, please fell free to submit a PR.
