### ISSUE TITLE
Are there plans to add TabbedPage?

### ISSUE THREAD

**Issue by maonaoda** [naveasy/Naveasy#8]

**Comment by ederbond** [comment]
Hi @maonaoda , sorry for the late reply. I'm kind of packed with my primary work now, so there's no plan to support TabbedPage for now, but if you would like to submit a PR I would be ver welcomed to review and merge it.

**Comment by ederbond** [comment]
For now, I think this plugin https://www.sharpnado.com/full-customizable-tabs-for-maui/ could be a nice alternative for those willing to implement Tabs.
