### ISSUE TITLE
Naveasy stops working on the .NET 8.0.403 with updated AndroidX libs

### ISSUE THREAD

**Issue by CyborTronik** [naveasy/Naveasy#9]
Depending on which libs you might use, but once some of AndroidX libs get updated the Naveasy 2.0.5 and 2.0.6 versions stop working.
An example of dependency is if you would use the latest versions of Firebase (`Xamarin.Firebase.Analytics`, `Xamarin.Firebase.Common`, `Xamarin.Firebase.Core`, and `Xamarin.Firebase.Crashlytics`) then transient libs related to `AndroidX` gets updated too and it affects the work of Naveasy. It's a high chance that there are some additional libs that could be involved and less trivial to debug.

I'm able to go to 1 page deep, and the second page cannot be routed after lib updates.

**Comment by ederbond** [comment]
@CyborTronik could you provide a sample with the steps to reproduce?
Does it works on previous versions?

**Comment by ederbond** [comment]
@CyborTronik have you checked that the code code block where you where triggering the navigation when you was having issues was actually running on the UI Thread? Maybe that would the the root cause (I'm just speculating). Page navigations must always be triggered from the main thread (UI Thread #1). Please check that and let me know.

**Comment by CyborTronik** [comment]
@ederbond it was in [RelyCommand] so normally it runs on the UI Thread as very any other navigations that I did

**Comment by ederbond** [comment]
Next time you notice it, please set a breakpoint into the line that starts the navigation and check on which thread it was. And also a breakpoint on the destination's Page and It's VM constructors and let me know it those breakpoints are getting hit also on which thread they where hitting that could gives us a hint on what could possibly be happening.

**Comment by ederbond** [comment]
Next time you notice it, please set a breakpoint into the line that starts the navigation and check on which thread it was. And also a breakpoint on the destination's Page and It's VM constructors and let me know it those breakpoints are getting hit also on which thread they where hitting that could gives us a hint on what could possibly be happening.
